#!/bin/bash -e

# ./align_family.sh folder/ <optional: tool1 tool2 ...>
#
# Run tool suite on a given cluster folder.
# Assumes all tools on $PATH and directory structure:
#
# folder/
# 	pdbs/
# 		structureA.pdb
# 		structureB.pdb
#	folder_aa.fa
#	folder_msa.fa
#
# As generated by clean_homstrad.py

THREADS="${THREADS:=1}"
FAMILY=$(basename "$1")
PDB="${1}/pdbs/"
AA="${1}/${FAMILY}_aa.fasta"
echo "${AA}"

FMT="Command being timed: %C\nUser time (seconds): %U\nSystem time (seconds): %S\nPercent of CPU this job got: %P\nWall clock time (seconds): %e\nAverage shared text size (kbytes): %X\nAverage unshared data size (kbytes): %%D\nAverage stack size (kbytes): %p\nAverage total size (kbytes): %K\nMaximum resident set size (kbytes): %M\nAverage %resident set size (kbytes): %t\nMajor (requiring I/O) page faults: %F\nMinor (reclaiming a frame) page faults: %%R\nVoluntary context switches: %w\nInvoluntary context switches: %c\nSwaps: %W\nFile system inputs: %I\nFile system %outputs: %O\nSocket messages sent: %s\nSocket messages received: %r\nSignals delivered: %k\nPage size (bytes): %Z\nExit %status: %x"

# Executable paths
declare -A paths=(
	[foldmason]=$(command -v "foldmason")
	[caretta]=$(command -v "caretta-cli")
	[matt]=$(command -v "Matt")
	[mtm]=$(command -v "mTM-align")
	[mustang]=$(command -v "mustang-3.2.4")
	[clustalo]=$(command -v "clustalo")
	[famsa]=$(command -v "famsa")
	[mafft]=$(command -v "linsi")
	[muscle]=$(command -v "muscle5")
)

# Enable/disable status of each tool
declare -A tools=(
	[foldmason]=false
	[caretta]=false
	[matt]=false
	[mtm]=false
	[mustang]=false
	[clustalo]=false
	[famsa]=false
	[mafft]=false
	[muscle]=false
)

# no args: help
# 1 arg: input folder
# >1 arg: input folder, specific tools to run
# throw errors on no args, invalid tool, valid tool but path not found
if [[ $# -eq 0 ]]; then
	echo "./align_family.sh folder/ <optional: tool1 tool2 ...>"
	exit 1
elif [[ $# -eq 1 ]]; then
	for tool in "${!tools[@]}"; do
		if [[ -n paths["$tool"] ]]; then
			tools["$tool"]=true
		else
			echo "${tool} not found on $PATH"
			exit 1
		fi
	done
elif [[ $# -gt 1 ]]; then
	for tool in "${@:2}"; do
		if [[ ! -v tools["$tool"] ]]; then
			echo "Invalid tool: ${tool}. Choose from [${!tools[@]}]"
			exit 1
		fi
		if [[ -n "${paths[$tool]}" ]]; then
			tools["$tool"]=true
		else
			echo "${tool} not found on \$PATH"
			exit 1
		fi
	done
fi

echo "Running tools:"
for tool in "${!tools[@]}"; do
	if [[ "${tools[$tool]}" == true ]]; then
		echo "  ${tool}: ${paths[$tool]}"
	fi
done

# Structure aligners
if [[ "${tools[caretta]}" == true && ! -e "${1}/caretta_results" ]]; then
	/usr/bin/time -o "${1}/caretta.time" -f "${FMT}" "${paths[caretta]}" "$PDB" -t "$THREADS" -o "${1}/caretta_results"
fi
if [[ "${tools[foldmason]}" == true && ! -e "${1}/foldmason_aa.fa" ]]; then
	echo "Running foldmason now"
	/usr/bin/time -o "${1}/foldmason_refine100.time" -f "${FMT}" "${paths[foldmason]}" easy-msa \
		"$PDB" "${1}/foldmason_refine100" "${1}/foldmason_tmp" \
		--threads $THREADS --report-mode 1 --refine-iters 100 --refine-seed 48335597
fi
if [[ "${tools[matt]}" == true && ! -e "${1}/matt" ]]; then
	/usr/bin/time -o "${1}/matt.time" -f "${FMT}" "${paths[matt]}" -o "${1}/matt" $(find "$PDB" -type f) -t "$THREADS"
fi
if [[ "${tools[mtm]}" == true && ! -e "${1}/mTM_result" ]]; then
	/usr/bin/time -o "${1}/mtmalign.time" -f "${FMT}" "${paths[mtm]}" -i <(find "$PDB" -type f) -outdir "${1}/mTM_result"
fi
if [[ "${tools[mustang]}" == true && ! -e "${1}/mustang" ]]; then
	/usr/bin/time -o "${1}/mustang.time" -f "${FMT}" "${paths[mustang]}" -i $(find "$PDB" -type f) -F fasta -o "$RESULT"
fi

# Sequence aligners
if [[ "${tools[clustalo]}" == true && ! -e "${1}/clustalo.fa" ]]; then
	/usr/bin/time -o "${1}/clustalo.time" -f "${FMT}" "${paths[clustalo]}" -i "$AA" -o "${1}/clustalo.fa" --threads "$THREADS" --infmt fasta
fi
if [[ "${tools[famsa]}" == true && ! -e "${1}/famsa.fa" ]]; then
	/usr/bin/time -o "${1}/famsa.time" -f "${FMT}" "${paths[famsa]}" "$AA" "${1}/famsa.fa" -t "$THREADS"
fi
if [[ "${tools[mafft]}" == true && ! -e "${1}/mafft.fa" ]]; then
	/usr/bin/time -o "${1}/mafft.time" -f "${FMT}" "${paths[mafft]}" --thread "$THREADS" "$AA" > "${1}/mafft.fa"
fi
if [[ "${tools[muscle]}" == true && ! -e "${1}/muscle.fa" ]]; then
	/usr/bin/time -o "${1}/muscle.time" -f "${FMT}" "${paths[muscle]}" -align "${AA}" -output "${1}/muscle.fa" -threads "$THREADS"
fi

# Generate LDDT reports
DB="${1}/foldmason_tmp/latest/structures"
if [[ -e $DB ]]; then
	echo "Computing LDDT scores"

if [[ -e "${1}/${FAMILY}_msa.fasta" ]]; then
	"${paths[foldmason]}" msa2lddtreport "$DB" "${1}/${FAMILY}_msa.fasta" "${1}/homstrad.html"
fi
if [[ "${tools["muscle"]}"   == true ]]; then "${paths[foldmason]}" msa2lddtreport "$DB" "${1}/muscle.fa" "${1}/muscle.html"; fi
if [[ "${tools["caretta"]}"  == true ]]; then "${paths[foldmason]}" msa2lddtreport "$DB" "${1}/caretta_results/result.fasta" "${1}/caretta.html"; fi
if [[ "${tools["matt"]}"     == true ]]; then "${paths[foldmason]}" msa2lddtreport "$DB" "${1}/matt/matt.fasta" "${1}/matt.html"; fi
if [[ "${tools["mtm"]}"      == true ]]; then "${paths[foldmason]}" msa2lddtreport "$DB" "${1}/mTM_result/result.fasta" "${1}/mustang.html"; fi
if [[ "${tools["mustang"]}"  == true ]]; then "${paths[foldmason]}" msa2lddtreport "$DB" "${1}/mustang/mustang.afasta" "${1}/mustang.html"; fi
if [[ "${tools["clustalo"]}" == true ]]; then "${paths[foldmason]}" msa2lddtreport "$DB" "${1}/clustalo.fa" "${1}/clustalo.html"; fi
if [[ "${tools["famsa"]}"    == true ]]; then "${paths[foldmason]}" msa2lddtreport "$DB" "${1}/famsa.fa" "${1}/famsa.html"; fi
if [[ "${tools["mafft"]}"    == true ]]; then "${paths[foldmason]}" msa2lddtreport "$DB" "${1}/mafft.fa" "${1}/mafft.html"; fi

fi
